In [1]:
import pandas as pd
import numpy as np

## 选择

In [2]:
df=pd.DataFrame(np.random.randn(6,4),index=pd.date_range('20180313',periods=6),columns=list('ABCD'))
df

A         B         C         D
2018-03-13 -1.258359 -1.011010  0.529580 -0.523306
2018-03-14 -0.480314  0.340523  0.874675  0.457142
2018-03-15 -1.341580 -0.735209 -0.140681 -1.315957
2018-03-16  0.983124 -0.215005 -0.612955  0.286917
2018-03-17 -0.059037 -1.034181  1.425688  1.611579
2018-03-18 -0.780211  0.659907 -0.744270  0.008312

In [3]:
df.A #或者 df['A']

2018-03-13   -1.258359
2018-03-14   -0.480314
2018-03-15   -1.341580
2018-03-16    0.983124
2018-03-17   -0.059037
2018-03-18   -0.780211
Freq: D, Name: A, dtype: float64

In [4]:
df[:2]

A         B         C         D
2018-03-13 -1.258359 -1.011010  0.529580 -0.523306
2018-03-14 -0.480314  0.340523  0.874675  0.457142

In [5]:
df.index

DatetimeIndex(['2018-03-13', '2018-03-14', '2018-03-15', '2018-03-16',
               '2018-03-17', '2018-03-18'],
              dtype='datetime64[ns]', freq='D')

In [6]:
df[ '2018-03-14':'2018-03-16']

A         B         C         D
2018-03-14 -0.480314  0.340523  0.874675  0.457142
2018-03-15 -1.341580 -0.735209 -0.140681 -1.315957
2018-03-16  0.983124 -0.215005 -0.612955  0.286917

In [7]:
df[ '20180312':'20180314']

A         B         C         D
2018-03-13 -1.258359 -1.011010  0.529580 -0.523306
2018-03-14 -0.480314  0.340523  0.874675  0.457142

### loc，iloc方式

In [8]:
df.loc['20180313']

A   -1.258359
B   -1.011010
C    0.529580
D   -0.523306
Name: 2018-03-13 00:00:00, dtype: float64

In [9]:
df.loc['20180313'].values

array([-1.25835912, -1.01100963,  0.52957991, -0.52330591])

In [10]:
df.loc[:'20180315',['A','B']]

A         B
2018-03-13 -1.258359 -1.011010
2018-03-14 -0.480314  0.340523
2018-03-15 -1.341580 -0.735209

In [11]:
df.loc['20180315','A']

-1.3415795058152549

In [12]:
df.iloc[2]

A   -1.341580
B   -0.735209
C   -0.140681
D   -1.315957
Name: 2018-03-15 00:00:00, dtype: float64

In [13]:
df.iloc[2 :4,: 2]

A         B
2018-03-15 -1.341580 -0.735209
2018-03-16  0.983124 -0.215005

In [14]:
df.iloc[[1,2,4],[0,2]]

A         C
2018-03-14 -0.480314  0.874675
2018-03-15 -1.341580 -0.140681
2018-03-17 -0.059037  1.425688

In [15]:
df.iloc[1,1]

0.34052291432152454

In [16]:
df.iat[1,1]

0.34052291432152454

### 使用布尔作为索引

In [17]:
df.A>0

2018-03-13    False
2018-03-14    False
2018-03-15    False
2018-03-16     True
2018-03-17    False
2018-03-18    False
Freq: D, Name: A, dtype: bool

In [18]:
(df.A>0).values

array([False, False, False,  True, False, False])

In [19]:
df[df.A>0]

A         B         C         D
2018-03-16  0.983124 -0.215005 -0.612955  0.286917

In [20]:
df>0

A      B      C      D
2018-03-13  False  False   True  False
2018-03-14  False   True   True   True
2018-03-15  False  False  False  False
2018-03-16   True  False  False   True
2018-03-17  False  False   True   True
2018-03-18  False   True  False   True

In [21]:
(df>0).values

array([[False, False,  True, False],
       [False,  True,  True,  True],
       [False, False, False, False],
       [ True, False, False,  True],
       [False, False,  True,  True],
       [False,  True, False,  True]])

In [22]:
df[df>0] # 结合 df.iloc[[1,2,4],[0,2]] 理解

A         B         C         D
2018-03-13       NaN       NaN  0.529580       NaN
2018-03-14       NaN  0.340523  0.874675  0.457142
2018-03-15       NaN       NaN       NaN       NaN
2018-03-16  0.983124       NaN       NaN  0.286917
2018-03-17       NaN       NaN  1.425688  1.611579
2018-03-18       NaN  0.659907       NaN  0.008312

In [23]:
df2=df.copy()

In [24]:
df2['E']=['one', 'one','two','three',np.nan,'four']

In [25]:
df2

A         B         C         D      E
2018-03-13 -1.258359 -1.011010  0.529580 -0.523306    one
2018-03-14 -0.480314  0.340523  0.874675  0.457142    one
2018-03-15 -1.341580 -0.735209 -0.140681 -1.315957    two
2018-03-16  0.983124 -0.215005 -0.612955  0.286917  three
2018-03-17 -0.059037 -1.034181  1.425688  1.611579    NaN
2018-03-18 -0.780211  0.659907 -0.744270  0.008312   four

In [26]:
s=df2['E'].isin(['two','four'])
s

2018-03-13    False
2018-03-14    False
2018-03-15     True
2018-03-16    False
2018-03-17    False
2018-03-18     True
Freq: D, Name: E, dtype: bool

In [27]:
df2[s]

A         B         C         D     E
2018-03-15 -1.341580 -0.735209 -0.140681 -1.315957   two
2018-03-18 -0.780211  0.659907 -0.744270  0.008312  four